version: '3'

services:
  frontend:
    container_name: vaxpred_frontend
    build:
      context: .
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
    depends_on:
      - backend

  backend:
    container_name: vaxpred_backend
    build:
      context: ./api
    volumes:
      - ./:/app
    ports:
      - "8123:8123"
