name: Backend Lint

on:
  pull_request:
  push:
    branches:
      # - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/VAXPRED/api

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8
