name: Deploy

on:
  pull_request:
  push:
    branches:
      # - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        push: true

    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
