name: AngularJS Tests

on:
  pull_request:
  push:
    branches:
      # - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/VAXPRED

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build -- --configuration=ci

      - name: Run AngularJS tests
        run: npm test -- --configuration=ci
