insert into user_plugin_association (user_id, plugin_id) values (1, 1);
insert into user_plugin_association (user_id, plugin_id) values (1, 2);
insert into user_plugin_association (user_id, plugin_id) values (1, 3);
insert into user_plugin_association (user_id, plugin_id) values (1, 4);
insert into user_plugin_association (user_id, plugin_id) values (1, 5);
insert into user_plugin_association (user_id, plugin_id) values (1, 6);
insert into user_plugin_association (user_id, plugin_id) values (2, 2);
insert into user_plugin_association (user_id, plugin_id) values (3, 3);
insert into user_plugin_association (user_id, plugin_id) values (4, 4);
insert into user_plugin_association (user_id, plugin_id) values (5, 5);
insert into user_plugin_association (user_id, plugin_id) values (6, 6);
insert into user_plugin_association (user_id, plugin_id) values (7, 7);
insert into user_plugin_association (user_id, plugin_id) values (8, 8);
insert into user_plugin_association (user_id, plugin_id) values (9, 9);
insert into user_plugin_association (user_id, plugin_id) values (10, 10);
insert into user_plugin_association (user_id, plugin_id) values (11, 11);
insert into user_plugin_association (user_id, plugin_id) values (12, 12);
insert into user_plugin_association (user_id, plugin_id) values (13, 13);
insert into user_plugin_association (user_id, plugin_id) values (14, 14);
insert into user_plugin_association (user_id, plugin_id) values (15, 15);
insert into user_plugin_association (user_id, plugin_id) values (16, 16);
insert into user_plugin_association (user_id, plugin_id) values (17, 17);
insert into user_plugin_association (user_id, plugin_id) values (18, 18);
insert into user_plugin_association (user_id, plugin_id) values (19, 19);
insert into user_plugin_association (user_id, plugin_id) values (20, 20);


insert into plugin_category_association (category_id, plugin_id) values (1, 1);
insert into plugin_category_association (category_id, plugin_id) values (2, 2);
insert into plugin_category_association (category_id, plugin_id) values (3, 3);
insert into plugin_category_association (category_id, plugin_id) values (4, 4);
insert into plugin_category_association (category_id, plugin_id) values (5, 5);
insert into plugin_category_association (category_id, plugin_id) values (1, 6);
insert into plugin_category_association (category_id, plugin_id) values (2, 7);
insert into plugin_category_association (category_id, plugin_id) values (3, 8);
insert into plugin_category_association (category_id, plugin_id) values (4, 9);
insert into plugin_category_association (category_id, plugin_id) values (5, 10);
insert into plugin_category_association (category_id, plugin_id) values (1, 11);
insert into plugin_category_association (category_id, plugin_id) values (2, 12);
insert into plugin_category_association (category_id, plugin_id) values (3, 13);
insert into plugin_category_association (category_id, plugin_id) values (4, 14);
insert into plugin_category_association (category_id, plugin_id) values (5, 15);
insert into plugin_category_association (category_id, plugin_id) values (0, 16);
insert into plugin_category_association (category_id, plugin_id) values (1, 17);
insert into plugin_category_association (category_id, plugin_id) values (2, 18);
insert into plugin_category_association (category_id, plugin_id) values (3, 19);
insert into plugin_category_association (category_id, plugin_id) values (4, 20);


INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('ProductivityMaster', '3.0', 'Boost your productivity with this amazing plugin', 'TechSolutions Inc.', 'TechSolutions Inc.', 'techsolutions@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('DataAnalyzer Pro', '2.5', 'Analyze data like a pro with this powerful tool', 'DataTech Labs', 'DataTech Labs', 'datatechlabs@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('SecurityGuard', '1.2', 'Enhance your system security with SecurityGuard', 'SecureSoft', 'SecureSoft', 'securesoft@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('MarketingGenius', '4.0', 'Supercharge your marketing efforts with MarketingGenius', 'MarketPros', 'MarketPros', 'marketpros@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('FinanceOptimizer', '2.1', 'Optimize your financial strategies with FinanceOptimizer', 'FinanceTech Solutions', 'FinanceTech Solutions', 'financetech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('SocialConnect', '2.0', 'Stay connected to your social networks with SocialConnect', 'SocialWare Inc.', 'SocialWare Inc.', 'socialware@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('InventoryMaster', '1.5', 'Manage your inventory efficiently with InventoryMaster', 'Inventory Systems Ltd.', 'Inventory Systems Ltd.', 'inventorysystems@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('ContentCreator Pro', '3.5', 'Create amazing content with ContentCreator Pro', 'CreativeTools', 'CreativeTools', 'creativetools@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('CustomerInsights', '2.2', 'Get valuable insights into your customers with CustomerInsights', 'Insightful Inc.', 'Insightful Inc.', 'insightfulinc@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('ProjectManager Plus', '4.1', 'Manage projects like a pro with ProjectManager Plus', 'Project Solutions Ltd.', 'Project Solutions Ltd.', 'projectsolutions@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('TimeTracker Pro', '1.0', 'Track your time efficiently with TimeTracker Pro', 'TimeTech Inc.', 'TimeTech Inc.', 'timetech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('CustomerSupportHero', '3.2', 'Provide top-notch customer support with CustomerSupportHero', 'SupportTech Solutions', 'SupportTech Solutions', 'supporttech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('SalesBooster', '2.8', 'Boost your sales with the SalesBooster plugin', 'SalesTech Pro', 'SalesTech Pro', 'salestech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('TaskManager Pro', '2.0', 'Efficiently manage tasks with TaskManager Pro', 'Task Solutions Ltd.', 'Task Solutions Ltd.', 'tasksolutions@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('HRMaster', '1.5', 'Streamline your HR processes with HRMaster', 'HR Tech Solutions', 'HR Tech Solutions', 'hrtech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('AnalyticsWizard', '4.2', 'Unlock powerful analytics with AnalyticsWizard', 'Data Insights Inc.', 'Data Insights Inc.', 'datainsights@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('E-commerceOptimizer', '3.1', 'Optimize your e-commerce business with E-commerceOptimizer', 'E-commerce Tech Pro', 'E-commerce Tech Pro', 'ecommercetech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('CustomerFeedbackPro', '2.6', 'Gather valuable customer feedback with CustomerFeedbackPro', 'FeedbackTech Inc.', 'FeedbackTech Inc.', 'feedbacktech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('InventoryTracker', '1.8', 'Track your inventory efficiently with InventoryTracker', 'InventoryTech Ltd.', 'InventoryTech Ltd.', 'inventorytech@gmail.com');
INSERT INTO plugins (name, version, description, developer, supplier_name, supplier_email) VALUES ('MarketingAnalytics', '3.0', 'Get in-depth marketing analytics with MarketingAnalytics', 'Marketing Insights Pro', 'Marketing Insights Pro', 'marketinginsights@gmail.com');



insert into categories (name) values ('Other');
insert into categories (name) values ('Virus');
insert into categories (name) values ('Bacteria');
insert into categories (name) values ('DNA');
insert into categories (name) values ('Machine Learning');



insert into users (username, email) values ('mfridaye0', 'esubhan0@narod.ru');
insert into users (username, email) values ('mdods1', 'bmartin1@cbslocal.com');
insert into users (username, email) values ('aspurrier2', 'jpethick2@arstechnica.com');
insert into users (username, email) values ('adorro3', 'ekippen3@parallels.com');
insert into users (username, email) values ('ctrewhela4', 'cdeblasiis4@bluehost.com');
insert into users (username, email) values ('sjallin5', 'afoulsham5@cdc.gov');
insert into users (username, email) values ('darnaudin6', 'rfrossell6@devhub.com');
insert into users (username, email) values ('cridgeway7', 'asaipy7@fastcompany.com');
insert into users (username, email) values ('rrourke8', 'bstainbridge8@cnet.com');
insert into users (username, email) values ('jmaryet9', 'hmcgready9@google.co.jp');
insert into users (username, email) values ('gdelmontea', 'aschwanda@wikimedia.org');
insert into users (username, email) values ('rgronaverb', 'gredmellb@nature.com');
insert into users (username, email) values ('hloudenc', 'mbrysonc@icio.us');
insert into users (username, email) values ('bheismand', 'cwisherd@disqus.com');
insert into users (username, email) values ('jquinete', 'lulstere@booking.com');
insert into users (username, email) values ('awhitelyf', 'cnealyf@arstechnica.com');
insert into users (username, email) values ('mverdeyg', 'fgniewoszg@chicagotribune.com');
insert into users (username, email) values ('psinclairh', 'ccanizaresh@salon.com');
insert into users (username, email) values ('awimsi', 'aneevesi@howstuffworks.com');
insert into users (username, email) values ('bbourkej', 'aclibberyj@unc.edu');
insert into users (username, email) values ('bheikkinenk', 'sholdink@example.com');
insert into users (username, email) values ('bjanicijevicl', 'ckirleyl@xrea.com');
insert into users (username, email) values ('astrydem', 'cglasbym@foxnews.com');
insert into users (username, email) values ('taveryn', 'kwoodhamn@paginegialle.it');
insert into users (username, email) values ('ahoodspetho', 'dwillbondo@purevolume.com');
insert into users (username, email) values ('esonghurstp', 'yhatwellp@ustream.tv');
insert into users (username, email) values ('bwrightemq', 'awallwoodq@purevolume.com');
insert into users (username, email) values ('askymer', 'wboardsr@samsung.com');
insert into users (username, email) values ('kdillways', 'bthornthwaites@blogtalkradio.com');
insert into users (username, email) values ('calsteadt', 'rzanussiit@walmart.com');
insert into users (username, email) values ('ijaksicu', 'veuleru@narod.ru');
insert into users (username, email) values ('vrowetv', 'sbarnardov@histats.com');
insert into users (username, email) values ('ifentyw', 'kpersew@yahoo.co.jp');
insert into users (username, email) values ('stootingx', 'lbrucksteinx@blogtalkradio.com');
insert into users (username, email) values ('kkillfordy', 'cstabley@adobe.com');
insert into users (username, email) values ('ztamburoz', 'tdjokovicz@bing.com');
insert into users (username, email) values ('bmcgeneay10', 'fstripp10@sciencedirect.com');
insert into users (username, email) values ('bneles11', 'cgavigan11@guardian.co.uk');
insert into users (username, email) values ('wygoe12', 'rmccoughan12@ed.gov');
insert into users (username, email) values ('sbonevant13', 'adoone13@devhub.com');
insert into users (username, email) values ('kjoslin14', 'gcrowch14@mayoclinic.com');
insert into users (username, email) values ('rhanwright15', 'mcloughton15@sitemeter.com');
insert into users (username, email) values ('dvonwelldun16', 'vlegendre16@ifeng.com');
insert into users (username, email) values ('dseegar17', 'gsharphouse17@ucsd.edu');
insert into users (username, email) values ('kshurrocks18', 'nhastilow18@bluehost.com');
insert into users (username, email) values ('mlawler19', 'hjanacek19@dyndns.org');
insert into users (username, email) values ('cmaytum1a', 'gsorrel1a@nytimes.com');
insert into users (username, email) values ('peastwood1b', 'mbonnell1b@etsy.com');
insert into users (username, email) values ('gjochens1c', 'egilbeart1c@imageshack.us');
insert into users (username, email) values ('hpancast1d', 'gboydell1d@facebook.com');
insert into users (username, email) values ('frucklesse1e', 'ccobain1e@columbia.edu');
insert into users (username, email) values ('rbaudin1f', 'tradage1f@state.gov');
insert into users (username, email) values ('dkinnerk1g', 'tkiln1g@usgs.gov');
insert into users (username, email) values ('takitt1h', 'cmervyn1h@engadget.com');
insert into users (username, email) values ('tsexton1i', 'nhissie1i@g.co');
insert into users (username, email) values ('gblair1j', 'vtax1j@vimeo.com');
insert into users (username, email) values ('epeach1k', 'hmarsters1k@state.gov');
insert into users (username, email) values ('slambal1l', 'ggilbanks1l@gravatar.com');
insert into users (username, email) values ('rolek1m', 'evassbender1m@shareasale.com');
insert into users (username, email) values ('bloude1n', 'abeumant1n@tmall.com');
insert into users (username, email) values ('cmonini1o', 'nohannay1o@forbes.com');
insert into users (username, email) values ('gchaffey1p', 'rtodor1p@issuu.com');
insert into users (username, email) values ('btebbs1q', 'jjekel1q@webnode.com');
insert into users (username, email) values ('hfranciottoi1r', 'tcarradice1r@independent.co.uk');
insert into users (username, email) values ('ahovell1s', 'ajancso1s@ebay.co.uk');
insert into users (username, email) values ('chuske1t', 'dbrawley1t@thetimes.co.uk');
insert into users (username, email) values ('kcowling1u', 'dvasilic1u@arstechnica.com');
insert into users (username, email) values ('btomkins1v', 'wrobart1v@google.com.au');
insert into users (username, email) values ('hfidge1w', 'frowdell1w@google.com.br');
insert into users (username, email) values ('lwarboy1x', 'cyurocjhin1x@wsj.com');
insert into users (username, email) values ('cdempster1y', 'nneighbour1y@wp.com');
insert into users (username, email) values ('tedelston1z', 'sshory1z@flickr.com');
insert into users (username, email) values ('mamdohr20', 'hvolker20@gov.uk');
insert into users (username, email) values ('abesant21', 'koloughane21@buzzfeed.com');
insert into users (username, email) values ('dsheryn22', 'rshingler22@toplist.cz');
insert into users (username, email) values ('alumby23', 'dfermor23@liveinternet.ru');
insert into users (username, email) values ('efoat24', 'jpeagram24@w3.org');
insert into users (username, email) values ('bmoyles25', 'hpuddifer25@marketwatch.com');
insert into users (username, email) values ('epalomba26', 'ctabard26@ted.com');
insert into users (username, email) values ('eperkinson27', 'dtremmel27@whitehouse.gov');
insert into users (username, email) values ('fhindge28', 'jgoodread28@storify.com');
insert into users (username, email) values ('dphillpot29', 'wmalinowski29@nps.gov');
insert into users (username, email) values ('dcrilley2a', 'epeizer2a@liveinternet.ru');
insert into users (username, email) values ('tcarren2b', 'mdebruijne2b@pcworld.com');
insert into users (username, email) values ('rspier2c', 'handreaccio2c@reuters.com');
insert into users (username, email) values ('ggarry2d', 'sfrantsev2d@ftc.gov');
insert into users (username, email) values ('mmacbeth2e', 'mdavern2e@yandex.ru');
insert into users (username, email) values ('hbratch2f', 'ntomley2f@upenn.edu');
insert into users (username, email) values ('cbygrave2g', 'hbruineman2g@dyndns.org');
insert into users (username, email) values ('jnelle2h', 'ascarsbrooke2h@google.co.jp');
insert into users (username, email) values ('rphippin2i', 'slambal2i@dailymotion.com');
insert into users (username, email) values ('edelacote2j', 'hbarszczewski2j@soundcloud.com');
insert into users (username, email) values ('wwhitehorne2k', 'kharsnipe2k@uiuc.edu');
insert into users (username, email) values ('mwinkworth2l', 'bgantley2l@microsoft.com');
insert into users (username, email) values ('mbubbear2m', 'vgirodier2m@nature.com');
insert into users (username, email) values ('ocattel2n', 'sspeare2n@tinyurl.com');
insert into users (username, email) values ('dmerrell2o', 'rarenson2o@japanpost.jp');
insert into users (username, email) values ('kmccullouch2p', 'grudsdell2p@marriott.com');
insert into users (username, email) values ('sbausor2q', 'wkyncl2q@photobucket.com');
insert into users (username, email) values ('elindfors2r', 'jglyne2r@salon.com');

