version: '3'

services:
  frontend:
    build:
      context: .
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
